### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleForAll#1]
Use the readme file from Accessible Web Dev as a template and copy the relevant parts over. Make sure to adjust all the links.

**Comment by Subham5401** [comment]
Hey @EmmaDawsonDev, I'd like to take this. Can you elaborate your requirement?

**Comment by EmmaDawsonDev** [comment]
Sure! 

If you delete everything that's in the readme now and replace it with the Contributing and License sections by copying from the AccessibleWebDev repository, that would be great. The links will need updating to point to this repository. 

I can add a project introduction and screenshot at a later date.

**Comment by CBID2** [comment]
Hi @EmmaDawsonDev! :) I noticed that Subham has not responded yet, so I created separate PRs(see the list below) to address this issue. I hope you don't mind. 
1. #13 
2. #14 
3. #15

**Comment by EmmaDawsonDev** [comment]
Hi @CBID2 I realize my explanation wasn't clear enough as this isn't quite what I meant.

If you look at the readme for Accessible Web Dev I meant that the Contributing and Licence sections there could be copy/pasted into this readme too and the links then just need updating to point at the contributing and licence files for this repo instead. Sorry for being unclear!

**Comment by CBID2** [comment]
> Hi @CBID2 I realize my explanation wasn't clear enough as this isn't quite what I meant.
> 
> 
> 
> If you look at the readme for Accessible Web Dev I meant that the Contributing and Licence sections there could be copy/pasted into this readme too and the links then just need updating to point at the contributing and licence files for this repo instead. Sorry for being unclear! 

Is [this the ReadMe](https://github.com/AccessibleForAll/AccessibleWebDev)I need to copy and paste from @EmmaDawsonDev?

**Comment by EmmaDawsonDev** [comment]
Yes, that's the one :)

**Comment by CBID2** [comment]
> Yes, that's the one :)

Hey @EmmaDawsonDev! :) I think I got it this time! :) Check [it out](https://github.com/AccessibleForAll/AccessibleForAll/pull/15)
