### ISSUE TITLE
Add coding standards

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleForAll#11]
Copy over the coding standards from [AccessibleWebDev](https://github.com/AccessibleForAll/AccessibleWebDev/blob/main/CODING_STANDARDS.md)

**Comment by wasup-yash** [comment]
i can work on this, and can you mention is there are any specifics that need to be changed or it also too same for this repo too.

**Comment by EmmaDawsonDev** [comment]
I think the file can just be copied, I don't see anything in there that's specific to the repository.
