### ISSUE TITLE
Update contributing guidelines

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleForAll#3]
Please copy the contributing guidelines from AccessibleWebDev repo and update the links for this repo.

**Comment by wasup-yash** [comment]
Hey, I would like to work on this issue... and to clarify we just to copy each step of `contributing guidelines from AccessibleWebDev` repo?

**Comment by EmmaDawsonDev** [comment]
Hi Yash! 

Yes, this project is set up in the same way so the instructions should be the same.

**Comment by wasup-yash** [comment]
hey, want to know that the `Languages` , `Pre-requisites (these need to be installed on your machine)` and `Available packages` would be totally the same as of [AccessibleWebDev](https://github.com/AccessibleForAll/AccessibleWebDev) repo ?

**Comment by EmmaDawsonDev** [comment]
Yes, they are all the same :)
