### ISSUE TITLE
Add github issue template

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleForAll#4]
Copy the github issue template from Accessible Web Dev and make any adjustments to links/names as necessary.

**Comment by wasup-yash** [comment]
hey i can work with this one too, but i didn't worked with templates before so i need the outline on how it needs to be done

**Comment by EmmaDawsonDev** [comment]
Sure! The Accessible Web Dev repo has some that can be copied, in the .github folder. Since you already created the .github folder in this repo they can be created directly there (outside of the workflow folder) with the same names.

**Comment by wasup-yash** [comment]
hey, do I need to branch out for this issue too in order to just add the issue template or I can add the template there only and create PR with the commit history of all the changes?

**Comment by EmmaDawsonDev** [comment]
It's always best to create a branch as it helps avoid merge conflicts on your fork

**Comment by wasup-yash** [comment]
> It's always best to create a branch as it helps avoid merge conflicts on your fork

Thanks for the suggestion :) and also should I create an issue regarding adding a feature template for this repo too as it is available for the web dev one?

**Comment by EmmaDawsonDev** [comment]
Ah yes, I hadn't realised the issue template was actually a folder containing two files. Feel free to make a separate issue if you want to otherwise you can do them both in the same PR as they are related (and I made a mistake when writing the issue)

**Comment by wasup-yash** [comment]
> Ah yes, I hadn't realised the issue template was actually a folder containing two files. Feel free to make a separate issue if you want to otherwise you can do them both in the same PR as they are related (and I made a mistake when writing the issue)

oh, so I will make the commit by adding both files.

**Comment by wasup-yash** [comment]
before creating PR I would like to ask if both files need should be of the same template for this repo too.

**Comment by EmmaDawsonDev** [comment]
> before creating PR I would like to ask if both files need to be of the same template for this repo too.

Yes, it should be fine that they are the same 👍
