### ISSUE TITLE
Add github pull request template

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleForAll#5]
Copy the github pull request template from Accessible Web Dev and make any adjustments to links/names as necessary.

**Comment by wasup-yash** [comment]
i can work on this too :)

**Comment by wasup-yash** [comment]
hey, I need to ask if all the points in the checklist are not valid for all the PRs as for some of the docs the running locally part is not necessary so we can add like `optional` to it as in if the contributor wants to remove it while making a PR.

**Comment by EmmaDawsonDev** [comment]
It's a checklist anyway so people can just not check the ones they haven't done. Maybe for the running locally one we can update it to say something like "I ran the app either locally or using a cloud-based service such as gitpod and verified my changes work as expected"

**Comment by wasup-yash** [comment]
yeah, this sounds good, will try this and then we can work on the PR if any changes require there only.

**Comment by wasup-yash** [comment]
Hey, before working on this issue I think we need to update `CONTRIBUTING.md` file as the hyperlink will point to it only, should I create an issue regarding that?

**Comment by CBID2** [comment]
> yeah, this sounds good, will try this and then we can work on the PR if any changes require there only.

Hi @wasup-yash! :) Let me know if you need help! :)

**Comment by wasup-yash** [comment]
> > yeah, this sounds good, will try this and then we can work on the PR if any changes require there only.
> 
> Hi @wasup-yash! :) Let me know if you need help! :)

Yeah totally,going to work on it today, been busy lately :)

**Comment by CBID2** [comment]
> > > yeah, this sounds good, will try this and then we can work on the PR if any changes require there only.
> 
> > 
> 
> > Hi @wasup-yash! :) Let me know if you need help! :)
> 
> 
> 
> Yeah totally,going to work on it today, been busy lately :) 

Alright! :)
