### ISSUE TITLE
Add github workflow - appreciation

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleForAll#6]
Copy the github workflow appreciation.yml from Accessible Web Dev and make any adjustments to links/names as necessary.

**Comment by wasup-yash** [comment]
hey we need to do the same as the [AccessibleWebDev](https://github.com/AccessibleForAll/AccessibleWebDev) right that you recently added? :)

**Comment by EmmaDawsonDev** [comment]
Yes. You want to try this one as well?

**Comment by wasup-yash** [comment]
Yes, this can be done quickly as i just need to copy the yaml file in the respective path right ?

**Comment by EmmaDawsonDev** [comment]
Yes, add a .github folder into the root of the project, inside that a workflows folder and then the yaml file inside there.

**Comment by wasup-yash** [comment]
Got it
